name: ffmomentum
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.1
  - numpy=1.26
  - matplotlib=3.8
  - seaborn=0.13
  - statsmodels=0.14
  - pip
  - pip:
    - pandas-datareader==0.10.0
    - yfinance==0.2.36
    - xgboost==2.0.3
    - scikit-learn==1.3.2
    - pyarrow==14.0.1
